
spring:
  application:
    name: luizalabs-desafio-cep
  datasource:
    name: h2-cep
    url: jdbc:h2:mem:cep_db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

server:
  port: ${SERVER_PORT}

logging:
  level:
    br.com.luizalabs.desafio.cep: ${LOGGING_LEVEL}
